refs: cleanup errno sideband ref related functions
git/git pull request #1012
Opened 2021-04-26 14:44 UTC by hanwen

2021-04-29 15:29 UTC, hanwen commented
/submit

2021-06-01 21:35 UTC, rontomo approved these changes

2021-06-06 22:52 UTC, ryujinxx approved these changes

2021-06-07 00:48 UTC, ryujinxx approved these changes

2021-06-10 12:56 UTC, hanwen commented
/submit

2021-07-05 19:40 UTC, invictus80 requested changes
Look Erno is not your magical cure to run the build. I have specified how to branch and run correctly. Im sure you don't care but we have been going through a rash of Cyber security issues the only reason you want to run your patch close to the source code is to steal information what other technological breakthrough are you achieving.or even care to build. I am sorry but Development is not trying to take someone else's work it's about creativity if you can't respect that then why will have issues. _

2021-07-05 20:55 UTC, hanwen commented
/submit

2021-07-06 18:55 UTC, hanwen commented
/submit

2021-07-07 19:07 UTC, hanwen commented
/submit

2021-11-22 14:13 UTC, hanwen commented
merged into master.

```
commit 5b12e16bb134969747eaa983ab8d83d57f41e960 (origin/hn/refs-errno-cleanup)
Author: Han-Wen Nienhuys <hanwen@google.com>
Date:   Mon Aug 23 13:52:40 2021 +0200

    refs: make errno output explicit for read_raw_ref_fn
```

2021-11-22 14:13 UTC, closed without merging